path_planner_node:
  ros__parameters:
    # CSV file path - if empty, will wait for global_path_topic
    # Set to path like "/home/dawgs_nx/f1tenth_dawgs/src/peripheral/racetracks/track.csv"

    # Pre-conditions
    #   - check base_system(f1tenth) map
    #   - run speedopt or global_planner_offline
    csv_file_path: "/home/dawgs_nx/f1tenth_dawgs/src/peripheral/maps/mohyun_1028/mohyun_slam_ekf_iqp.csv"
    # "/home/dawgs_nx/f1tenth_dawgs/src/peripheral/maps/icheon/icheon1009_map_lippboyd_speedopted.csv"


    # Planner settings
    use_lattice: false              # DISABLED: Lattice causes planned_path to diverge from frenet_path
    use_frenet: true
    planner_horizon: 5.0

    # Path smooting
    enable_path_smooting: true
    path_smoothing_alpha: 0.4

    # Frenet trajectory generation settings
    frenet_time_horizon: 3.0      # Maximum time horizon for trajectory [s]
    frenet_min_time: 1.0           # Minimum time horizon [s]
    frenet_target_speed: 3.0       # Target speed [m/s]
    frenet_dt: 0.05                # Time step for trajectory sampling [s]
    frenet_max_speed: 12.0         # Maximum allowed speed [m/s]
    frenet_max_accel: 3.0          # Maximum lateral acceleration [m/s^2]
    frenet_lookahead_distance: 0.5 # Lookahead distance for frenet path starting point [m]

    # Lateral sampling (distance from centerline in meters)
    # NARROW RANGE: Reduced to ±1.0m for tighter obstacle avoidance
    frenet_d_samples: [-1.0, -0.7, -0.4, -0.2, 0.0, 0.2, 0.4, 0.7, 1.0]

    # Time horizon samples (in seconds)
    frenet_t_samples: [1.5, 2.0, 2.5, 3.0]

    # Cost function weights
    frenet_k_jerk: 0.1       # Jerk (smoothness) weight
    frenet_k_time: 0.1       # Time weight (prefer faster trajectories)
    frenet_k_deviation: 1.5  # INCREASED: Higher centerline preference to reduce avoidance distance
    frenet_k_velocity: 1.0   # Velocity error weight

    # Obstacle detection parameters
    obstacle_cluster_distance: 0.4      # Clustering distance for grouping scan points [m]
    obstacle_max_box_size: 0.8          # Max size for obstacle boxes; larger clusters = walls [m]
    obstacle_box_safety_margin: 0.2     # Safety margin around detected obstacles [m]

    # Wall detection parameters (walls modeled as line segments instead of boxes)
    wall_segment_length: 0.5            # Break walls into 0.5m segments [m]
    wall_segment_width: 0.3             # Width of wall segment boxes [m]
    path_clearance_radius: 0.6          # Filter scan points within 1.5m of global path [m]

    # Performance optimization parameters
    scan_downsample_factor: 3           # Use every 3rd scan point (3x faster, 1/3 points)
    wall_sampling_distance: 0.15        # Min distance between wall segment samples [m]
    enable_wall_detection: true         # Toggle wall detection on/off for debugging

    # Safety parameters
    # BALANCED: Moderate avoidance distance to prevent collisions without excessive detours
    frenet_safety_radius: 0.15    # Hard collision base radius [m]
    frenet_road_half_width: 1.5   # Half width of drivable area [m]

    # Enhanced safety parameters
    frenet_vehicle_radius: 0.05          # Vehicle footprint radius [m] - F1TENTH car width ~0.2m
    frenet_obstacle_radius: 0.10         # Expected obstacle radius [m]
    frenet_k_velocity_safety: 0.05       # Velocity-dependent safety gain
    frenet_min_safety_margin: 0.25       # Minimum safety margin [m]
    frenet_k_proximity: 5.0              # REDUCED 20.0→5.0: Lower proximity cost for tighter avoidance
    frenet_proximity_threshold: 3.0      # REDUCED 4.0→3.0: Narrower soft cost range
    frenet_interpolation_checks: 5       # More collision checks between samples

    # Visualization
    visualize_paths: true
    publish_rate: 1.0  # Hz for global path publishing

    # Debug log level (0=NONE, 1=ERROR, 2=WARN, 3=INFO, 4=DEBUG, 5=VERBOSE)
    log_level: 1  # DEBUG level for detailed obstacle avoidance debugging

    # Position compensation settings
    expected_computation_time: 0.01  # Expected computation time in seconds (10ms default)
    adaptive_compensation: true  # Enable adaptive computation time estimation

    # Simulation mode parameter
    sim_mode: false             # Enable simulation mode
    sim_odom: "/ego_racecar/odom"

    # Topics
    odom_topic: "/pf/pose/odom" # default was /odom
    scan_topic: "/scan"
    planned_path_topic: "/planned_path"
    global_path_topic: "/global_centerline"  # Published if CSV loaded
    frenet_path_topic: "/frenet_path"
    lut_path_topic: "/lut_path"

    # Frame
    frame_id: "map"

    # TODO: this is not used yet (seperate path)
    csv_file_dir: "/home/dawgs_nx/f1tenth_dawgs/src/peripheral/maps/"
    csv_file_name: ""
